default_language_version:
  python: python3
repos:
- repo: https://github.com/pycqa/isort
  rev: '5.13.2'
  hooks:
  - id: isort
    exclude: 'settings'
- repo: https://github.com/psf/black
  rev: '23.12.0'
  hooks:
  - id: black
    exclude: 'migrations*|urls*|settings*|setup.py'
- repo: https://github.com/pycqa/flake8
  rev: '6.1.0'
  hooks:
  - id: flake8
    # NB The "exclude" setting in setup.cfg is ignored by pre-commit
    exclude: 'migrations*|urls*|settings*'
