dist: bionic
language: python
python:
  - "3.7"
cache: pip

#before_install:

services:
  - redis-server

install:
  - pip install -r requirements_dev.txt

before_script:
  - pip install flake8 sphinx

script:
  - pytest
  - flake8
#  - sphinx-build -nW docs docs/_build/html
