version: '3.0'

services:

  redis:
    image: redis:6-alpine
    expose: 
      - 6379

  asyncio_rpc:
    build:
      context: ./
      dockerfile: Dockerfile  
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./:/code
