name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - display_name: "2019"
            python: 3.8
            os: ubuntu-20.04
            pins: ""
          - display_name: "2020"
            python: 3.9
            os: ubuntu-20.04
            pins: ""
          - display_name: "2021"
            python: 3.9
            os: ubuntu-20.04
            pins: ""
          - display_name: "2022"
            python: '3.10'
            os: ubuntu-22.04
            pins: ""
          - display_name: "latest"
            python: '3.10'
            os: ubuntu-latest
            pins: ""

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools wheel
          pip install -e .[numpy,test] ${{ matrix.pins }} ipython pytest pytest-asyncio flake8 
          pip list

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 5
          redis-remove-container: true # false by default

      - name: Run tests
        shell: bash
        run: |
          pytest
